### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by eisenlaub** [alexras/bread#3]
The current codebase isn't python 3.x ready yet. Would be great to have it though!

**Comment by cyberic99** [comment]
We have a python 3.x compatible fork here, without breaking python2:
https://github.com/TheOtherDays/bread

alexras, would you like a pull request?

**Comment by alexras** [comment]
Yes, please send it!

**Comment by alexras** [comment]
Python 3 support has been integrated as of 1.5.3.
