### ISSUE TITLE
Bread is really slow for some data structures

### ISSUE THREAD

**Issue by alexras** [alexras/bread#5]
The crux of the issue, I think, is that bread isn't great at demarshaling and marshaling a lot of small structures.

Really, the structures bread produces should be dealing with the underlying binary data as lazily as possible; indexing into them when needed rather than aggressively unpacking the bit strings into objects.

**Comment by cyberic99** [comment]
i see.
And do you have plans to implement such a feature?

**Comment by alexras** [comment]
Yes. A patch is already in progress.

On Monday, January 19, 2015, cyberic99 <notifications@github.com> wrote:

> i see.
> And do you have plans to implement such a feature?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexras/bread/issues/5#issuecomment-70482585>.
>


-- 
Sent from my phone.

**Comment by alexras** [comment]
2.1 should resolve the most glaring speed issues; pylsdj's test time is about 10x faster than it was.
