### ISSUE TITLE
Regression from 1.5.3 to 2.1.12

### ISSUE THREAD

**Issue by cyberic99** [alexras/bread#7]
Hello

I just had some old code using bread, designed for an old version of bread.
I recently updated bread, and with the new version the code is not working anymore:

With bread version 1.5.1 (commit bc0acd4862df92d297eeda3043cad66747f7a7a6), I was able to do that:
```
    data={
            "_default_instr_byte_1": 208,
            "_default_instr_byte_2": 243,
            "automate_1": False,
            "automate_2": False,
            "envelope": 1,
            "has_sound_length": True,
            "instrument_type": "pulse",
            "pan": "L",
            "phase_finetune": 0,
            "phase_transpose": 0,
            "sound_length": 46,
            "sweep": 255,
            "table": 3,
            "table_on": True,
            "vibrato": {
                "direction": "down",
                "type": 0
            },
            "wave": 0}

    data=dict_to_obj(data)
    print(data)
    bb=bread.write(data, bread_spec.instrument)
    print(bb)
```
(dict_to_obj takes a dict and returns an object with "dict_to_obj" type)

Now, with the latest bread, I get this error:
```
ValueError: Object to write must be a structure created by bread.parse
```
So I added: 
```
    aa=bread.parse(data, bread_spec.instrument)
```

And this time, I got this error:
```
TypeError: Cannot initialise bitstring from <type 'type'>.
```

In fact, I have a json file describing  object, and I would like bread to parse it, and to return an object.

**Comment by alexras** [comment]
You can accomplish what you want with the `new()` operator, introduced in v2.2.0. See http://bread.readthedocs.org/en/latest/parsing.html#creating-empty-objects for more information.

It also looks like you're dealing with a pylsdj instrument; you're aware that instruments can read and write themselves as JSON, right?

**Comment by cyberic99** [comment]
Thank you!
the new() is a great addition.
About instruments, yes I am aware. 
The code I posted was just an example to reproduce the problem as clearly as possible.

Thank you for your quick addition!

**Comment by cyberic99** [comment]
Thank you for you addition, but could you please consider adding an extra arg to the constructor, to be able to make a new struct, but already initialised instead of using default values?
For instance:
```
format_spec = [("greeting", b.string(5)),  ("age", b.nibble)]
empty_struct = b.new(format_spec)
empty_struct.greeting = 'hello'
empty_struct.age = 0xb

second_struct = b.new(format_spec, init_from=empty_struct)
```

Thanks

**Comment by alexras** [comment]
Please open this as a separate issue so that I can track it separately. Thanks!
